name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # or another version you prefer
    - name: Lint and Format
      run: |
        cd ./client
        npm ci
        npm run lint
        npm run format
        cd ..

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # or another version you prefer
    - name: Test Server
      run: |
        cd ./server
        npm ci
        npm run test
        cd ..

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  # or another version you prefer
    - name: Build Client
      run: |
        cd ./client
        npm ci
        npm run build-only
        cd ..